language: rust
sudo: false
cache: cargo

notifications:
  email: false

branches:
  only:
    # Enable building pull requests.
    - master
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying

rust:
- 1.26.0
- stable
- beta
- nightly

env:
- FEATURES=""
- FEATURES=chrono
- FEATURES=json
- FEATURES=all

script:
  - |
    set -e
    if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      cargo clean --verbose
    fi
    if [ "$FEATURES" = all ]; then
      FEATURES_COMMAND="--all-features"
    elif [ -n $FEATURES ]; then
      FEATURES_COMMAND="--features="$FEATURES
    else
      FEATURES_COMMAND="--no-default-features"
    fi
    cargo build --verbose ${FEATURES_COMMAND}
    cargo test --verbose ${FEATURES_COMMAND}
