[package]
name = "serde_with"
version = "0.1.0"
authors = ["jonasbb"]

description = "Placeholder for a collection of useful de/serialize_with functions"
documentation = "https://docs.rs/serde_with/"
repository = "https://github.com/jonasbb/serde_with"
readme = "README.md"
keywords = ["serde", "utilities"]
license = "MIT/Apache-2.0"

[features]
json = [ "serde_json" ]

[dependencies]
chrono = { version = "0.4.2", features = [ "serde" ], optional = true }
serde = "1.0.59"
serde_json = { version = "1.0.17", optional = true }

[dev-dependencies]
serde_derive = "1.0.59"
serde_json = "1.0.17"
pretty_assertions = "0.5.1"
